### PR TITLE
Update minikube version to v0.28.0

### PR DESCRIPTION
**Pull request by mestery**
This relates to #138 since we'll have to keep a close eye on the removal of localkube.

Signed-off-by: Kyle Mestery <mestery@mestery.com>

### CODE REVIEW

**Comment by mestery** [comment]
I am also testing this locally, but in lieu of #131, we'll likely want this as well.

**Comment by sbezverk** [comment]
@mestery Curious why not 1.11? the rest looks good.

**Comment by mestery** [comment]
@sbezverk Minikube does not yet support Kubernetes 1.11, once it does we'll update this.

**Comment by sbezverk** [comment]
@mestery cool, thanks 
/LGTM

**Pull request merged**
