### PR TITLE
fix typo in README

### PR DESCRIPTION
**Pull request by vielmetti**
Very small change to correct a typo in the README and to say hello to @fkautz @mestery @edwarnicke and thanks for today's call.

### CODE REVIEW

**Comment by mestery** [comment]
Thanks for the patch @vielmetti! You're missing the DCO sign-off, see here [1] for how to add that. :)

https://github.com/probot/dco#how-it-works

**Comment by edwarnicke** [comment]
@vielmetti Looks like you need  a Signed-off-by line

**Comment by vielmetti** [comment]
hm, these look like they have "Signed-off-by: Edward Vielmetti <ed@packet.net>" but the DCO is still failing.

**Comment by ondrej-fabry** [comment]
@vielmetti Only 3 out of 6 commits include "Signed-off-by ...". For the DCO check to pass, all commits in the PR have to include it.

**Comment by vielmetti** [comment]
ACK

I am traveling today, and will be PTO next week, so in the interests of not having open ended issues, I'm going to close this for now (and reopen when I'm prepared to sit down with git.

FIN

**Pull request closed without merging**
