### PR TITLE
Converting generate-sriov-configmap to plugin

### PR DESCRIPTION
**Pull request by fkautz**

### CODE REVIEW

**Comment by fkautz** [comment]
Currently a WIP, do not merge yet.

**Comment by sbezverk** [comment]
I have a couple of concerns with proposed plugin approach:
1. How does a cluster admin triggers configmap generation if it runs as a plugin? Also how it can be re-run as VFs config can be changed dynamically on the host and without reboot it. So it is possible that cluster admin would need to re-run to to build updated configmap.
2. configmap generator also scans and re-binds VF from their drivers to vfio, running this process in a container would require additional mounts for /sys, /proc and /dev. It is a security concern as this will make a pod running it as a super root. I am not sure if cluster admins would be happy with such power hungry POD.

**Comment by fkautz** [comment]
1. This doesn't change how you run it. It still generates a binary and you call it the same way as you do before. The main difference is instead of running everything in main(), it lives in a plugin and can explicitly wiire+configure dependencies like the kubernetes client, cobra/viper, logger, etc... in a way that is uniform with the rest of the project.

2. Same thing as above, this doens't change where you run it. If it doesn't run in a container today, this patch doesn't change that.

I can delay converting this to a plugin if you are actively making changes and come back to this at a later time, so that we don't create conflicts.

**Comment by sbezverk** [comment]
@fkautz No, I am not making any major changes, so no conflict here. I am just trying to understand how to use it when it becomes a plugin. Appreciate if you could give an example so it would be easier for me to visualize it.

**Pull request closed without merging**
